Fix regression in post-gen hook
The recent fix for contributed languages didn’t take into account
pending changes in the post-gen hook. That caused the following error:

> ERROR: Stopping generation because post_gen_project hook script didn't exit successfully

Fix this issue by pointing the post-gen hook to the new file locations.